---
- name: "Installing apache webserver"
  hosts: 192.168.37.18,192.168.37.19,192.168.37.20,192.168.37.21
  become: yes
  tasks:
    - name: Installing a package
      yum:
        name: httpd
        state: present

    - name: Start and enable a service
      service:
        state: started
        name: httpd
        enabled: yes

    - name: Add firewall rule
      firewalld:
        state: enabled
        service: httpd
        permanent: yes
        immediate: yes

    - name: Add index.html file
      copy:
        dest: /var/www/html/index.html
        content: "This is webserver we created with ansible"

    # - name: Remove index.html file
    #   file:
    #     path: var/www/html/index.html"
    #     state: absent

    # - name: Remove firewall rule
    #   firewalld:
    #     state: disabled
    #     service: http
    #     permanent: yes
    #     immediate: yes
        
    # - name: Stop and disable a service
    #   service:
    #     state: stopped
    #     name: httpd
    #     enabled: no

    # - name: Uninstalling a package
    #   yum:
    #     name: httpd
    #     state: absent